import streamlit as st
import os
from pathlib import Path

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Model Demonstrations", layout="wide")

# --- INJECT CUSTOM CSS ---
def local_css(file_name):
    if Path(file_name).exists():
        with open(file_name) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

css_path = Path(__file__).parent.parent / "style.css"
local_css(css_path)

def main():
    st.title("Model Demonstrations")
    
    st.markdown("""
    <div class="glass-container">
        <p>This page showcases the integration of multiple custom-trained computer vision models. 
        The videos below demonstrate the system's ability to extract high-level tactical information 
        from raw broadcast footage.</p>
    </div>
    """, unsafe_allow_html=True)
    
    PROJECT_ROOT = Path(__file__).parent.parent.parent
    
    # Define the paths to the annotated videos
    demo_vid_model_large = PROJECT_ROOT / "demo_videos" / "prem_vid_annotated_web.mp4"
    demo_vid_model_small = PROJECT_ROOT / "demo_videos" / "prem_vid_annotated_short_web.mp4"
    
    # Section 1: YOLO11x Professional Tracking
    st.header("Large Model Architecture: YOLO11x")
    st.markdown("<p>The YOLO11x model provides maximum detection precision and tracking stability. This demonstration focuses on player localization and consistent identity preservation across the entire field of view.</p>", unsafe_allow_html=True)
    
    if demo_vid_model_large.exists():
        st.video(str(demo_vid_model_large))
        
        with open(demo_vid_model_large, 'rb') as vf:
            st.download_button(
                label="Download YOLO11x Demonstration",
                data=vf,
                file_name="yolo11x_demonstration.mp4",
                mime="video/mp4"
            )
    else:
        st.error(f"Demonstration asset not found at {demo_vid_model_large.name}.")
    
    st.markdown("---")
    
    # Section 2: YOLO8n Tactical Mapping
    st.header("Integrated Pipeline: YOLOv8n with Tactical Mapping")
    st.markdown("""
    <p>This demonstration combines detection, keypoint-based registration, and team classification. 
    The 2D tactical minimap in the corner is dynamically generated by projecting 2D camera coordinates 
    onto a metric pitch representation through a RANSAC-optimized homography matrix.</p>
    """, unsafe_allow_html=True)
    
    if demo_vid_model_small.exists():
        st.video(str(demo_vid_model_small))
        
        with open(demo_vid_model_small, 'rb') as vf:
            st.download_button(
                label="Download Integrated Pipeline Demonstration",
                data=vf,
                file_name="yolov8n_integrated_demo.mp4",
                mime="video/mp4"
            )
    else:
        st.error(f"Demonstration asset not found at {demo_vid_model_small.name}.")

    st.markdown("""
    <div class="app-footer">
        2D Virtual Mapping System &nbsp;|&nbsp; Shepherd University CIS Capstone Project - Peyton Hollis, Curtis Canby, Uchenna Ibe &nbsp;|&nbsp; Built with Streamlit and Ultralytics YOLO, utlizes SoccerNet and Roboflow datasets. 
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()
